// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk2WOCLk6iSKfWXZE7f9OWoSIr-k4dbVU',
    appId: '1:840388755212:web:d50f99d6ce03ed138e5329',
    messagingSenderId: '840388755212',
    projectId: 'chat-app-69783',
    authDomain: 'chat-app-69783.firebaseapp.com',
    storageBucket: 'chat-app-69783.appspot.com',
    measurementId: 'G-7SVWZBTF0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZPIy7zt9K9Ss9oRNniV73VkE73E51jPw',
    appId: '1:840388755212:android:f3923265f3e3e7188e5329',
    messagingSenderId: '840388755212',
    projectId: 'chat-app-69783',
    storageBucket: 'chat-app-69783.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjShLvXXPWQIYghflgtkS9mVL4eOJExn0',
    appId: '1:840388755212:ios:2448f4dd8f105b178e5329',
    messagingSenderId: '840388755212',
    projectId: 'chat-app-69783',
    storageBucket: 'chat-app-69783.appspot.com',
    iosBundleId: 'com.example.proj1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjShLvXXPWQIYghflgtkS9mVL4eOJExn0',
    appId: '1:840388755212:ios:427a75a5c24825a88e5329',
    messagingSenderId: '840388755212',
    projectId: 'chat-app-69783',
    storageBucket: 'chat-app-69783.appspot.com',
    iosBundleId: 'com.example.proj1.RunnerTests',
  );
}
